In [197]:
import pandas as pd

In [198]:
import numpy as np

In [199]:
R = pd.read_csv("C:\\Users\\user\\Documents\\r_matrix.csv", header = None)

In [200]:
R = np.matrix(R)


In [201]:
R

matrix([[ -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,   0,  -1,  -1,  -1,   0,  -1,  -1,  -1, 100],
        [  0,  -1,  -1,  -1,   0,  -1,   0,  -1,  -1,  -1],
        [ -1,  -1,  -1,   0,  -1,   0,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,   0,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,   0, 100],
        [ -1,  -1,  -1,  -1,  -1,  -1,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,   0,  -1, 100]], dtype=int64)

In [202]:
Q = np.zeros((10,10))

In [203]:
Q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [204]:
gamma =0.7

In [205]:
initial_state = 2

In [206]:
def avl_actions(state):
    current_state_row =R[state,]
    av_act =np.where(current_state_row >= 0)[1]
    return av_act



In [207]:
available_actions = avl_actions(initial_state)

In [208]:
available_actions

array([1, 5, 9], dtype=int64)

In [209]:
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_actions_range,1))
    return next_action

#def sample_next_action(available_actions_range):
#    next_action = int(np.random.choice(available_act,1))
#    return next_action


In [210]:
action = sample_next_action(available_actions)

In [211]:
action

5

In [212]:
def update(current_state,action,gamma):
    
    max_index = np.where(Q[action,] == np.max(Q[action,]))[0]
    
    if max_index.shape[0] > 1:
        max_index =int(np.random.choice(max_index,size = 1))
    else:
        max_index =int(max_index)
        
    max_value=Q[action,max_index]
        
    Q[current_state,action] = R[current_state,action] + gamma*max_value
    
    
   

In [213]:
update(initial_state,action,gamma)

In [214]:
Q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [215]:
for i in range(15000):
    current_state =np.random.randint(0,int(Q.shape[0]))
    available_act =avl_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)

In [216]:
print((Q / np.max(Q)) * 100)

[[  0.     0.     0.    34.3    0.     0.     0.     0.     0.     0.  ]
 [  0.     0.    70.     0.     0.     0.     0.     0.     0.     0.  ]
 [  0.    49.     0.     0.     0.    49.     0.     0.     0.   100.  ]
 [ 24.01   0.     0.     0.    49.     0.    24.01   0.     0.     0.  ]
 [  0.     0.     0.    34.3    0.    49.     0.    70.     0.     0.  ]
 [  0.     0.    70.     0.    49.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.    34.3    0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.    49.     0.     0.     0.    49.   100.  ]
 [  0.     0.     0.     0.     0.     0.     0.    70.     0.     0.  ]
 [  0.     0.    70.     0.     0.     0.     0.    70.     0.   100.  ]]


In [217]:
#goal state = 9
#starting state =6
#best sequence that I am expecting fro 6 = 6_> 3-> 4 -> 7-> 9

In [220]:
current_state =6
steps = [current_state]

while current_state != 9:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]
    
    if next_step_index.shape[0] > 1:
        next_step_index =int(np.random.choice(next_step_index,size = 1))
    else:
        next_step_index =int(next_step_index)
        
    steps.append(next_step_index)
    current_state =next_step_index
        
print("The chosen path for the mouse is:")
print(steps)
        
    

The chosen path for the mouse is:
[6, 3, 4, 7, 9]
